Select FileName, Domain from dbo.DomainByFilename Where
FileName in ('Prelytix_ServiceNowProspectsNeverAttended_TargetAcctList_100614.Txt',
'Prelytix_ServiceNowCustAttend_TargetAcctList_100614.Txt',
'Prelytix_ServiceNowProspectAttend_TargetAcctList_100614.Txt',
'Prelytix_ServiceNowCustomersNeverAttended_TargetAcctList_100614.Txt',
'MRP_SiebelAcctData_9292014.Txt')
